{
 "title": "Kafka Streams Dashboard",
 "description": "Dashboard for a Kafka Streams application using Prometheus JMX-Exporter running in Kubernetes",
 "tags": [
  "Kafka Streams",
  "Prometheus",
  "Kubernetes",
  "Streams",
  "Kafka"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "App",
    "query": {
     "query": "label_values(kafka_streams_kafka_metrics_count_count,app)"
    }
   },
   {
    "name": "Instance",
    "query": {
     "query": "label_values(kafka_consumer_group_ConsumerLagMetrics_Value,instance)"
    }
   },
   {
    "name": "topic",
    "query": {
     "query": "label_values(kafka_consumer_group_ConsumerLagMetrics_Value,topic)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Node Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Streams Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {}
   ]
  },
  {
   "title": "OffsetLag",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
   "targets": [
    {
     "expr": "kafka_consumer_group_ConsumerLagMetrics_Value{instance=~\"${Instance:pipe}\",name=\"OffsetLag\",topic=\"${topic}\"}",
     "legendFormat": "{{groupId}}"
    }
   ]
  },
  {
   "title": "EstimatedMaxTimeLag",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
   "targets": [
    {
     "expr": "kafka_consumer_group_ConsumerLagMetrics_Value{instance=~\"${Instance:pipe}\",name=\"EstimatedMaxTimeLag\",topic=\"${topic}\"}",
     "legendFormat": "{{groupId}}"
    }
   ]
  },
  {
   "title": "SumOffsetLag",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "kafka_consumer_group_ConsumerLagMetrics_Value{instance=~\"${Instance:pipe}\",name=\"SumOffsetLag\",topic=\"${topic}\"}",
     "legendFormat": "{{groupId}}"
    }
   ]
  },
  {
   "title": "EstimatedTimeLag",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "kafka_consumer_group_ConsumerLagMetrics_Value{instance=~\"${Instance:pipe}\",name=\"EstimatedTimeLag\",topic=\"${topic}\"}",
     "legendFormat": "{{groupId}}"
    }
   ]
  },
  {
   "title": "MaxOffsetLag",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "kafka_consumer_group_ConsumerLagMetrics_Value{instance=~\"${Instance:pipe}\",name=\"MaxOffsetLag\",topic=\"${topic}\"}",
     "legendFormat": "{{groupId}}"
    }
   ]
  }
 ]
}