{
 "title": "narwhal",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "pending_orders",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "pending_orders{}", "legendFormat": "__auto" }
   ]
  },
  { "title": "message", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "message_his_margin",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    { "expr": "message_his_margin", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "message_deal",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    { "expr": "message_deal", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "message_his_order",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    { "expr": "message_his_order", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "message_usermsg_liq",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "targets": [
    { "expr": "message_usermsg_liq", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "message_his_position",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "targets": [
    { "expr": "message_his_position", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "message_usermsg_adl",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "targets": [
    { "expr": "message_usermsg_adl", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "message_usermsg_liqalert",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "targets": [
    { "expr": "message_usermsg_liqalert", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "message_preference",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "targets": [
    { "expr": "message_preference", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "message_his_deal",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "targets": [
    { "expr": "message_his_deal", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "message_position",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
   "targets": [
    { "expr": "message_position", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "message_his_system",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 49 },
   "targets": [
    { "expr": "message_his_system", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Panel Title",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 12, "y": 49 },
   "targets": [
    { "expr": "message_his_funding", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "message_his_balance",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 57 },
   "targets": [
    { "expr": "message_his_balance", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "message_balance",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 11, "y": 57 },
   "targets": [
    { "expr": "message_balance", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "message_order",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 65 },
   "targets": [
    { "expr": "message_order", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "message_market",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 11, "y": 65 },
   "targets": [
    { "expr": "message_market", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "cmd",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 73 },
   "collapsed": true,
   "panels": [
    {
     "title": "cmd_order_cancel_all",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 11, "x": 0, "y": 10 },
     "targets": [
      { "expr": "cmd_order_cancel_all", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "cmd_postion_limit_close",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 13, "x": 11, "y": 10 },
     "targets": [
      { "expr": "cmd_postion_limit_close", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "pending_position_users",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 11, "x": 0, "y": 16 },
     "targets": [
      { "expr": "pending_position_users", "legendFormat": "{{scope}}" }
     ]
    },
    {
     "title": "pending_order_users",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 13, "x": 11, "y": 16 },
     "targets": [
      { "expr": "pending_order_users", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "cmd_order_put_limit",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 11, "x": 0, "y": 22 },
     "targets": [
      { "expr": "cmd_order_put_limit", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "cmd_order_cancel",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 13, "x": 11, "y": 22 },
     "targets": [
      { "expr": "cmd_order_cancel", "legendFormat": "__auto" }
     ]
    }
   ]
  }
 ]
}