{
 "title": "做市账户数据监控",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Asset", "label": "资产", "query": "USDT,USTT" },
   { "name": "Start", "label": "开始时间", "query": "${VAR_START}" }
  ]
 },
 "panels": [
  {
   "title": "今日0点资金费",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "dear",
     "rawSql": "select sum(amount)\nfrom maker_position_funding_history where asset = \"$Asset\" and floor(time) = UNIX_TIMESTAMP(CAST(SYSDATE()AS DATE));"
    }
   ]
  },
  {
   "title": "昨日累计已实现盈亏",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "dear",
     "rawSql": "select sum(`change`) as profit from maker_balance_history where asset = \"$Asset\" and business = \"trade\" and floor(`time`) >= unix_timestamp(\"$Start\") and floor(`time`) < UNIX_TIMESTAMP(CAST(SYSDATE()AS DATE));"
    }
   ]
  },
  {
   "title": "当日已实现盈亏",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "dear",
     "rawSql": "select sum(`change`) as profit from maker_balance_history where asset = \"$Asset\" and business = \"trade\" and TO_DAYS(from_unixtime(floor(`time`))) = TO_DAYS(now());\n"
    }
   ]
  },
  {
   "title": "当日资金费盈亏",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "dear",
     "rawSql": "select sum(amount)\nfrom maker_position_funding_history where asset = \"$Asset\" and floor(time) >= UNIX_TIMESTAMP(CAST(SYSDATE()AS DATE)) - 8*3600 and floor(time) <= UNIX_TIMESTAMP(CAST(SYSDATE()AS DATE)) + 8*3600;"
    }
   ]
  },
  {
   "title": "今日8点资金费",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "dear",
     "rawSql": "select sum(amount)\nfrom maker_position_funding_history where asset = \"$Asset\" and floor(time) > UNIX_TIMESTAMP(CAST(SYSDATE()AS DATE)) and floor(time) <= UNIX_TIMESTAMP(CAST(SYSDATE()AS DATE)) + 8 * 3600;\n"
    }
   ]
  },
  {
   "title": "今日累计已实现盈亏",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "dear",
     "rawSql": "select sum(`change`) as profit from maker_balance_history where asset = \"$Asset\" and business = \"trade\" and floor(`time`) >= unix_timestamp(\"$Start\");"
    }
   ]
  },
  {
   "title": "单日已实现盈亏记录",
   "type": "table",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 6 },
   "targets": [
    {
     "dataset": "dear",
     "rawSql": "select b.atime as time,b.sum_change as profit from (select UNIX_TIMESTAMP(CAST(from_unixtime(floor(maker_balance_history.`time`)) AS DATE)) as atime,\n                                     sum(`change`) as sum_change\n                              from maker_balance_history\n                              where asset = \"$Asset\"\n                                and business = \"trade\"\n                                and floor(`time`) >= unix_timestamp(\"$Start\")\n                              group by atime\n                              order by atime desc\n) as b"
    }
   ]
  },
  {
   "title": "资金费用记录",
   "type": "table",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 6 },
   "targets": [
    {
     "dataset": "dear",
     "rawSql": "select floor(`time`) as time, sum(amount) as funding\nfrom maker_position_funding_history where asset = \"$Asset\" and floor(`time`) >= unix_timestamp(\"$Start\") group by floor(time) order by floor(`time`) desc;\n"
    }
   ]
  },
  {
   "title": "昨日16点资金费",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "dear",
     "rawSql": "select sum(amount)\nfrom maker_position_funding_history where asset = \"$Asset\" and floor(time) >= UNIX_TIMESTAMP(CAST(SYSDATE()AS DATE)) - 8*3600 and floor(time) < UNIX_TIMESTAMP(CAST(SYSDATE()AS DATE));\n\n"
    }
   ]
  },
  {
   "title": "头寸监控",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(contract) (maker_position_sum_monitor{asset=\"$Asset\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "浮动盈亏",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(contract) (maker_position_profit_unreal_sum_monitor{asset=\"$Asset\"})",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}