{
 "title": "用户盈亏监控",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Asset", "label": "资产", "query": "USDT,USTT" },
   { "name": "Days", "label": "天数", "query": "1,3,7,30" },
   { "name": "Start", "label": "开始时间", "query": "${VAR_START}" }
  ]
 },
 "panels": [
  {
   "title": "用户总手续费",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "dear",
     "rawSql": "select sum(abs(`change`)) as total_fee from user_balance_history where business = \"fee\" and asset = \"$Asset\" and floor(`time`) >= unix_timestamp(\"$Start\");"
    }
   ]
  },
  {
   "title": "用户风险基金",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "dear",
     "rawSql": "select sum(b.total) as total_risk from (select total from user_insurance_history where asset = \"$Asset\" and floor(`time`) >= unix_timestamp(\"$Start\") order by id limit 1) as b"
    }
   ]
  },
  {
   "title": "用户累计手续费记录",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "dataset": "dear",
     "rawSql": "select b.atime as time,b.sum_change as fee from (select UNIX_TIMESTAMP(CAST(from_unixtime(floor(user_balance_history.`time`)) AS DATE)) as atime,\n                                                           sum(abs(`change`)) as sum_change\n                                                    from user_balance_history\n                                                    where asset = \"$Asset\"\n                                                      and business = \"fee\"\n                                                      and floor(`time`) >= unix_timestamp(\"$Start\")\n                                                    group by atime\n                                                    order by atime desc\n                                                   ) as b"
    }
   ]
  },
  {
   "title": "$Days天已实现盈亏 手续费",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "dataset": "dear",
     "rawSql": "select p.user_id, sum(`change`) as profit, abs(b.fee) as fee from user_balance_history as p left join (select user_id, sum(`change`) as fee from user_balance_history where business = \"fee\" and asset = \"$Asset\" and `time` > (unix_timestamp() - $Days * 24 * 3600) and floor(`time`) >= unix_timestamp(\"$Start\") group by user_id)\n    as b on b.user_id = p.user_id where p.business = \"trade\" and p.asset = \"$Asset\" and p.`time` > (unix_timestamp() - $Days * 24 * 3600) and floor(p.`time`) >= unix_timestamp(\"$Start\") group by p.user_id order by profit desc limit 50;"
    }
   ]
  }
 ]
}