{
 "title": "做市账户数据监控",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   { "name": "Asset", "label": "资产", "query": "USDT,USTT" },
   { "name": "Start", "label": "开始时间", "query": "2023-06-01 00:00:00" },
   { "name": "Days", "label": "天数", "query": "1,3,7,30" }
  ]
 },
 "panels": [
  {
   "title": "今日0点资金费",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "dear",
     "rawSql": "select sum(funding)\nfrom maker_position_funding_history where asset = \"$Asset\" and floor(time) = UNIX_TIMESTAMP(CAST(SYSDATE()AS DATE));"
    }
   ]
  },
  {
   "title": "总权益",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "maker_equity_sum_monitor{asset=\"$Asset\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "总盈亏",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "maker_pnl_sum_monitor{asset=\"$Asset\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "总资金费",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select sum(funding) as funding from maker_position_funding_history where asset = \"$Asset\";\n"
    }
   ]
  },
  {
   "title": "今日8点资金费",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "dear",
     "rawSql": "select sum(funding)\nfrom maker_position_funding_history where asset = \"$Asset\" and `time` > (UNIX_TIMESTAMP(CAST(SYSDATE()AS DATE)) + 4 * 3600) and `time` < (UNIX_TIMESTAMP(CAST(SYSDATE()AS DATE)) + 12 * 3600);\n "
    }
   ]
  },
  {
   "title": "昨日累计已实现盈亏",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select sum(`change`) as profit from maker_balance_history where asset = \"$Asset\" and business = \"trade\" and `time` < (UNIX_TIMESTAMP() - MOD(UNIX_TIMESTAMP(), 86400));\n"
    }
   ]
  },
  {
   "title": "今日已实现盈亏",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "dear",
     "rawSql": "select sum(`change`) as profit from maker_balance_history where asset = \"$Asset\" and business = \"trade\" and `time` >= (UNIX_TIMESTAMP() - MOD(UNIX_TIMESTAMP(), 86400));\n"
    }
   ]
  },
  {
   "title": "今日资金费盈亏",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "dear",
     "rawSql": "select sum(funding)\nfrom maker_position_funding_history where asset = \"$Asset\" and `time` > (UNIX_TIMESTAMP(CAST(SYSDATE()AS DATE)) - 4*3600) and `time` < (UNIX_TIMESTAMP(CAST(SYSDATE()AS DATE)) + 20*3600);"
    }
   ]
  },
  {
   "title": "昨日16点资金费",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "dear",
     "rawSql": "select sum(funding)\nfrom maker_position_funding_history where asset = \"$Asset\" and `time` > (UNIX_TIMESTAMP(CAST(SYSDATE()AS DATE)) - 12 * 3600) and `time` < UNIX_TIMESTAMP(CAST(SYSDATE()AS DATE));\n\n"
    }
   ]
  },
  {
   "title": "今日累计已实现盈亏",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "dear",
     "rawSql": "select sum(`change`) as profit from maker_balance_history where asset = \"$Asset\" and business = \"trade\";"
    }
   ]
  },
  {
   "title": "每日已实现盈亏",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 8 },
   "targets": [
    {
     "dataset": "dear",
     "rawSql": "select b.atime as time,b.sum_change as profit from (select UNIX_TIMESTAMP(CAST(from_unixtime(floor(maker_balance_history.`time`)) AS DATE)) as atime,\n                                     sum(`change`) as sum_change\n                              from maker_balance_history\n                              where asset = \"$Asset\"\n                                and business = \"trade\"\n                                and `time` > (unix_timestamp() - $Days * 24 * 3600)     \n                              group by atime\n                              order by atime desc\n) as b"
    }
   ]
  },
  {
   "title": "每日资金费",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 8 },
   "targets": [
    {
     "dataset": "dear",
     "rawSql": "select floor(`time`) as time, sum(funding) as funding\nfrom maker_position_funding_history where asset = \"$Asset\" and `time` > (unix_timestamp() - $Days * 24 * 3600) group by floor(`time`) order by `time` desc;\n"
    }
   ]
  },
  {
   "title": "头寸监控",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(contract) (maker_position_sum_monitor{asset=\"$Asset\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "浮动盈亏",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(contract) (maker_position_profit_unreal_sum_monitor{asset=\"$Asset\"})",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}